#!/usr/bin/env Rscript
# ── Meaningful-drift detector ─────────────────────────────────────────────────
# Decides whether a nightly refresh actually changed the study, or merely
# reran it.
#
# Several artifacts differ on every run regardless of the data: PROVENANCE.md
# and mysterycall_evaluation.md stamp a generation time and the current git
# SHA, and ggplot re-renders PNG/TIFF with different bytes each time. Treating
# those as drift would open a pull request every night forever, which trains
# reviewers to ignore nightly PRs -- the opposite of the point.
#
# Exit 0 = meaningful drift (open a PR). Exit 1 = cosmetic only (do nothing).

volatile_line <- function(x) {
  grepl("^Generated:", x) |
  grepl("^Analysis repo:", x) |
  grepl("^- mysterycall version:", x) |
  # per-run identifiers: the analysis commit changes on every commit, so it
  # differs on every nightly regardless of whether any result moved
  grepl("\"(labubu_commit|analysis_commit|git_sha|generated_at|created)\"", x) |
  # provenance table rows carry a per-run "Created" timestamp
  grepl("[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}", x)
}

# Presentation artifacts are regenerated byte-differently every run; their
# content is fully determined by the CSVs and the report, which ARE compared.
cosmetic_path <- function(path) {
  grepl("\\.(png|tiff|docx|html)$", path, ignore.case = TRUE)
}

changed_paths <- system2("git", c("diff", "--staged", "--name-only"),
                         stdout = TRUE)
changed_paths <- changed_paths[nzchar(changed_paths)]

if (!length(changed_paths)) {
  base::message("DRIFT: none (no staged changes)")
  quit(status = 1)
}

normalise <- function(lines) {
  lines <- lines[!volatile_line(lines)]
  lines[nzchar(trimws(lines))]
}

meaningful <- character(0)
for (path in changed_paths) {
  if (cosmetic_path(path)) next
  previous <- suppressWarnings(
    system2("git", c("show", paste0("HEAD:", path)), stdout = TRUE,
            stderr = FALSE))
  current <- if (file.exists(path)) readLines(path, warn = FALSE) else character(0)
  if (!identical(normalise(previous), normalise(current)))
    meaningful <- c(meaningful, path)
}

if (!length(meaningful)) {
  base::message("DRIFT: cosmetic only (", length(changed_paths),
                " file(s) changed: timestamps and re-rendered figures)")
  base::message("  no pull request needed")
  quit(status = 1)
}

base::message("DRIFT: meaningful, in ", length(meaningful), " file(s)")
for (path in meaningful) base::message("  ", path)
quit(status = 0)
