#!/usr/bin/env Rscript
# ── Meaningful-drift detector ─────────────────────────────────────────────────
# Decides whether a nightly refresh actually changed the study, or merely
# reran it.
#
# Several artifacts differ on every run regardless of the data: PROVENANCE.md
# and mysterycall_evaluation.md stamp a generation time and the current git
# SHA, and ggplot re-renders PNG/TIFF with different bytes each time. Treating
# those as drift would open a pull request every night forever, which trains
# reviewers to ignore nightly PRs -- the opposite of the point.
#
# Exit 0 = meaningful drift (open a PR). Exit 1 = cosmetic only (do nothing).

volatile_line <- function(x) {
  grepl("^Generated:", x) |
  grepl("^Analysis repo:", x) |
  grepl("^- mysterycall version:", x) |
  grepl("^Package repo:", x) |
  # The API writes a new timestamped export filename on every pull, so the
  # filename churns even when the MD5 and row count are identical. The MD5 is
  # the identity that matters and is compared on its own line.
  grepl("LABUBU_DATA(_LABELS)?_[0-9]{4}-[0-9]{2}-[0-9]{2}_[0-9]{4}\\.csv", x) |
  # per-run identifiers: the analysis commit changes on every commit, so it
  # differs on every nightly regardless of whether any result moved
  grepl("\"(labubu_commit|analysis_commit|git_sha|generated_at|created)\"", x) |
  # provenance table rows carry a per-run "Created" timestamp
  grepl("[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}", x)
}

# Presentation artifacts are regenerated byte-differently every run; their
# content is fully determined by the CSVs and the report, which ARE compared.
cosmetic_path <- function(path) {
  grepl("\\.(png|tiff|docx|html)$", path, ignore.case = TRUE) |
  # estimands.csv is judged by estimand-diff.R, which knows that interval
  # bounds are far less numerically stable than point estimates and holds them
  # to their own tolerance. Comparing it here too would apply the wrong rule
  # and re-introduce the noise this script exists to suppress.
  grepl("estimands\\.csv$", path)
}

changed_paths <- system2("git", c("diff", "--staged", "--name-only"),
                         stdout = TRUE)
changed_paths <- changed_paths[nzchar(changed_paths)]

if (!length(changed_paths)) {
  base::message("DRIFT: none (no staged changes)")
  quit(status = 1)
}

normalise <- function(lines) {
  lines <- lines[!volatile_line(lines)]
  lines[nzchar(trimws(lines))]
}

# Two lines that differ only in the low-order digits of their numbers are the
# same result computed on a different machine. A BLAS or optimiser difference
# moved a caller-adjusted coefficient in the sixth decimal and opened a
# pull request over it; the estimands were byte-identical.
NUMERIC_RE <- "-?[0-9]+\\.?[0-9]*([eE][-+]?[0-9]+)?"
REL_TOLERANCE <- 1e-4

numerically_equivalent <- function(a, b) {
  if (identical(a, b)) return(TRUE)
  # The non-numeric skeleton must match exactly; only digits may differ.
  if (!identical(gsub(NUMERIC_RE, "#", a), gsub(NUMERIC_RE, "#", b)))
    return(FALSE)
  a_nums <- suppressWarnings(as.numeric(
    regmatches(a, gregexpr(NUMERIC_RE, a))[[1]]))
  b_nums <- suppressWarnings(as.numeric(
    regmatches(b, gregexpr(NUMERIC_RE, b))[[1]]))
  if (length(a_nums) != length(b_nums)) return(FALSE)
  if (!length(a_nums)) return(TRUE)
  both_na <- is.na(a_nums) & is.na(b_nums)
  if (any(is.na(a_nums) != is.na(b_nums))) return(FALSE)
  a_nums <- a_nums[!both_na]; b_nums <- b_nums[!both_na]
  if (!length(a_nums)) return(TRUE)
  denominator <- pmax(abs(a_nums), .Machine$double.eps)
  all(abs(a_nums - b_nums) / denominator <= REL_TOLERANCE)
}

content_equivalent <- function(previous, current) {
  if (length(previous) != length(current)) return(FALSE)
  all(mapply(numerically_equivalent, previous, current))
}

meaningful <- character(0)
for (path in changed_paths) {
  if (cosmetic_path(path)) next
  previous <- suppressWarnings(
    system2("git", c("show", paste0("HEAD:", path)), stdout = TRUE,
            stderr = FALSE))
  current <- if (file.exists(path)) readLines(path, warn = FALSE) else character(0)
  if (!content_equivalent(normalise(previous), normalise(current)))
    meaningful <- c(meaningful, path)
}

if (!length(meaningful)) {
  base::message("DRIFT: cosmetic only (", length(changed_paths),
                " file(s) changed: timestamps, re-rendered figures, ",
                "and numbers within ", format(REL_TOLERANCE), " relative tolerance)")
  base::message("  no pull request needed")
  quit(status = 1)
}

base::message("DRIFT: meaningful, in ", length(meaningful), " file(s)")
for (path in meaningful) base::message("  ", path)
quit(status = 0)
